### ISSUE TITLE
python 3 there is a issue with opencv library 

### ISSUE THREAD

**Issue by AldrinCode** [haydenbanz/DiscordGloom#1]
It seems like you're encountering an issue related to qpencv and Python 3. To help you resolve this issue, I'll need more information about the specific problem you're facing. 

Please provide the following details:

1. The error message you're encountering when trying to use qpencv with Python 3.
2. The steps you've already taken to install or configure qpencv.
3. Any relevant code or configuration files related to your usage of qpencv.

With this information, I'll be able to provide more targeted assistance to help you resolve the issue.

**Comment by h9zdev** [comment]
To resolve the issue with qpencv and Python 3, you can follow these general troubleshooting steps:

1. **Check Compatibility**: Ensure that the version of qpencv you are using is compatible with Python 3. Some libraries may have different versions for Python 2 and Python 3.

2. **Update qpencv**: If you are using an older version of qpencv, consider updating it to the latest version that supports Python 3. You can usually update Python packages using pip:

   ```bash
   pip install --upgrade qpencv
   ```

3. **Check Dependencies**: qpencv may have dependencies on other libraries or packages. Make sure that all required dependencies are installed and up-to-date.

4. **Python Environment**: Ensure that you are using the correct Python environment. Sometimes, issues can occur if you have multiple Python installations or virtual environments.

5. **Check System Libraries**: Some Python packages may rely on system libraries. Ensure that the necessary system libraries are installed and accessible.

6. **Error Message**: Pay attention to the specific error message you are encountering. It can provide valuable information about what exactly is going wrong. Share the error message if you need further assistance.

7. **Community Support**: Check if there is a community or user group for qpencv where you can ask for help. Sometimes, other users may have encountered and solved similar issues.

8. **Alternative Libraries**: If you continue to face issues, consider looking for alternative libraries or solutions that provide similar functionality to qpencv and are better maintained for Python 3.

9. **Python Version**: Make sure you are using a compatible version of Python 3. qpencv may not work with very old versions of Python 3.

10. **Consult Documentation**: Refer to the official documentation or README of qpencv for any specific instructions or troubleshooting tips related to Python 3 compatibility.

If you provide more specific details about the error message or the steps you've already taken, I can offer more targeted advice.
