### ISSUE TITLE
The webserver function is not working in the bot.py

### ISSUE THREAD

**Issue by VaradScript** [haydenbanz/DiscordGloom#14]
# Bug Report

**Project:** [HadesConnect](https://github.com/haydenbanz/HadesConnect)  
**Repository URL:** https://github.com/haydenbanz/HadesConnect

## Description

*When the /start_server command is given, the server fails to start and returns a socket error.*

**Comment by haybnzz** [comment]
now it's been fixed`@bot.command()
async def start_server(ctx):
    # Create an asyncio loop for the web server and WebSocket server
    loop = asyncio.get_event_loop()

    # Create and start the web server
    async def web_server():
        app = web.Application()
        async def hello(_):
            return web.Response(text="Hello, world")
        app.add_routes([web.get('/', hello)])
        runner = web.AppRunner(app)
        await runner.setup()
        site = web.TCPSite(runner, 'localhost', 8080)
        await site.start()
        await ctx.send("Web server started at http://localhost:8080")

    # Create and start the WebSocket server
    async def websocket_server(websocket, _):
        while True:
            message = await websocket.recv()
            print(f"Received message: {message}")
            await websocket.send(f"Echo: {message}")

    # Run both servers concurrently
    loop.create_task(web_server())
    start_server = websockets.serve(websocket_server, "localhost", 8765)
    loop.run_until_complete(start_server)
    await ctx.send("WebSocket server started at ws://localhost:8765")`

**Comment by h9zdev** [comment]
fixed now`@bot.command()
async def start_server(ctx):
    # Create an asyncio loop for the web server and WebSocket server
    loop = asyncio.get_event_loop()

    # Create and start the web server
    async def web_server():
        app = web.Application()
        async def hello(_):
            return web.Response(text="Hello, world")
        app.add_routes([web.get('/', hello)])
        runner = web.AppRunner(app)
        await runner.setup()
        site = web.TCPSite(runner, 'localhost', 8080)
        await site.start()
        await ctx.send("Web server started at http://localhost:8080")

    # Create and start the WebSocket server
    async def websocket_server(websocket, _):
        while True:
            message = await websocket.recv()
            print(f"Received message: {message}")
            await websocket.send(f"Echo: {message}")

    # Run both servers concurrently
    loop.create_task(web_server())
    start_server = websockets.serve(websocket_server, "localhost", 8765)
    loop.run_until_complete(start_server)
    await ctx.send("WebSocket server started at ws://localhost:8765")`
