### ISSUE TITLE
THERE WAS EEOR SHOW FFMEG WHILE !VOICE_GET COMMAND

### ISSUE THREAD

**Issue by Glitchesminds** [haydenbanz/DiscordGloom#7]
The error indicates that the ffmpeg executable is not found. ffmpeg is used by Discord.py to handle voice operations, such as playing audio.

**Comment by haydenbanz** [comment]
The error indicates that the `ffmpeg` executable is not found. `ffmpeg` is used by Discord.py to handle voice operations, such as playing audio.

To fix this, you need to install `ffmpeg` and make sure it's accessible from your system's PATH. Here's how you can do it:

1. **Install ffmpeg**: You can download it from the official website ([ffmpeg.org](https://ffmpeg.org/download.html)) or use a package manager like Homebrew (for macOS) or Chocolatey (for Windows). For example, on Windows, you can use Chocolatey to install ffmpeg by running the following command in your command prompt or PowerShell:

   ```
   choco install ffmpeg
   ```

   On macOS, you can use Homebrew:

   ```
   brew install ffmpeg
   ```

2. **Add ffmpeg to your system's PATH**: After installing ffmpeg, make sure it's added to your system's PATH environment variable. This allows Discord.py to locate the ffmpeg executable.

Once you've installed ffmpeg and added it to your PATH, restart your Python script or the command prompt/terminal window where your bot is running, and the issue should be resolved.

**Comment by haydenbanz** [comment]
The error indicates that the `ffmpeg` executable is not found. `ffmpeg` is used by Discord.py to handle voice operations, such as playing audio.

To fix this, you need to install `ffmpeg` and make sure it's accessible from your system's PATH. Here's how you can do it:

1. **Install ffmpeg**: You can download it from the official website ([ffmpeg.org](https://ffmpeg.org/download.html)) or use a package manager like Homebrew (for macOS) or Chocolatey (for Windows). For example, on Windows, you can use Chocolatey to install ffmpeg by running the following command in your command prompt or PowerShell:

   ```
   choco install ffmpeg
   ```

   On macOS, you can use Homebrew:

   ```
   brew install ffmpeg
   ```

2. **Add ffmpeg to your system's PATH**: After installing ffmpeg, make sure it's added to your system's PATH environment variable. This allows Discord.py to locate the ffmpeg executable.

Once you've installed ffmpeg and added it to your PATH, restart your Python script or the command prompt/terminal window where your bot is running, and the issue should be resolved.

**Comment by h9zdev** [comment]
The error indicates that the `ffmpeg` executable is not found. `ffmpeg` is used by Discord.py to handle voice operations, such as playing audio.

To fix this, you need to install `ffmpeg` and make sure it's accessible from your system's PATH. Here's how you can do it:

1. **Install ffmpeg**: You can download it from the official website ([ffmpeg.org](https://ffmpeg.org/download.html)) or use a package manager like Homebrew (for macOS) or Chocolatey (for Windows). For example, on Windows, you can use Chocolatey to install ffmpeg by running the following command in your command prompt or PowerShell:

   ```
   choco install ffmpeg
   ```

   On macOS, you can use Homebrew:

   ```
   brew install ffmpeg
   ```

2. **Add ffmpeg to your system's PATH**: After installing ffmpeg, make sure it's added to your system's PATH environment variable. This allows Discord.py to locate the ffmpeg executable.

Once you've installed ffmpeg and added it to your PATH, restart your Python script or the command prompt/terminal window where your bot is running, and the issue should be resolved.
